// This is a generated file. Do not modify this. You'll lose it all one day and will be sad. It's generated by the boilermaker process from files contained in ../plugins/.

#include "asset.h"
#include "assets.mesh.h"
#include "assets.image.h"
#include "assets.shader.h"

using namespace std;
using namespace overground;


static std::unique_ptr<Asset> makeAsset(asset::asset_t const & desc)
{
  if (desc.data.valueless_by_exception() == false)
  {
    auto typeIdx = desc.data.index();
    switch(typeIdx)
    {
    case 0: // Mesh
      return std::make_unique<Mesh>(desc);
    case 1: // Image
      return std::make_unique<Image>(desc);
    case 2: // Shader
      return std::make_unique<Shader>(desc);
    }
  }

  return std::make_unique<Asset>(desc);
}
