// This is a generated file. Do not modify this. You'll lose it all one day and will be sad. It's generated by the boilermaker process from files contained in ../plugins/.

#include "feature.h"
#include "features.matrixTransform.h"
#include "features.srtTransform.h"
#include "features.drawableModel.h"
#include "features.directionalLight.h"
#include "features.pointLight.h"
#include "features.spotLight.h"
#include "features.camera.h"

using namespace std;
using namespace overground;


static std::unique_ptr<Feature> makeFeature(tableau::feature_t const & desc)
{
  if (desc.data.valueless_by_exception() == false)
  {
    auto typeIdx = desc.data.index();
    switch(typeIdx)
    {
    case 0: // MatrixTransform
      return std::make_unique<MatrixTransform>(desc);
    case 1: // SrtTransform
      return std::make_unique<SrtTransform>(desc);
    case 2: // DrawableSubmodel
      return std::make_unique<DrawableSubmodel>(desc);
    case 3: // DrawableModel
      return std::make_unique<DrawableModel>(desc);
    case 4: // DirectionalLight
      return std::make_unique<DirectionalLight>(desc);
    case 5: // PointLight
      return std::make_unique<PointLight>(desc);
    case 6: // SpotLight
      return std::make_unique<SpotLight>(desc);
    case 7: // Camera
      return std::make_unique<Camera>(desc);
    }
  }

  return std::make_unique<Feature>(desc);
}
