// This is a generated file. Do not modify this. You'll lose it all one day and will be sad. It's generated by the boilermaker process from files contained in ../plugins/.

#include "object.h"
// #include "plugins/builtin/object.otherKindOfObject.h"

using namespace std;
using namespace overground;


static std::unique_ptr<Object> makeObject(tableau::object_t const & desc)
{
  if (desc.data.has_value())
  {
    auto typeIdx = desc.data->index();
    switch(typeIdx)
    {
//    case 0: // otherKindOfObject      
//      return std::make_unique<OtherKindOfObject>(desc);
    }
  }

  return std::make_unique<Object>(desc);
}
