// This is a generated file. Do not modify this. You'll lose it all one day and will be sad. It's generated by the boilermaker process from files contained in ../plugins/.

#include "object.h"
#include "objects.otherKindOfObject.h"

  using namespace std;
  using namespace overground;


  std::unique_ptr<Object> makeObject(tableau::object_t const & desc)
  {
  if (desc.data.has_value() &&
      desc.data->valueless_by_exception() == false)
  {
      auto typeIdx = desc.data->index();
      switch(typeIdx)
      {
      case 0: // OtherKindOfObject
      return std::make_unique<OtherKindOfObject>(desc);
    }
  }

  return std::make_unique<Object>(desc);
}
